force-app/main/default/objects/Person__c/fields/Bonus__c.field-meta.xml
<CustomField>
    <fullName>Bonus__c</fullName>
    <defaultValue>0</defaultValue>
    <label>Bonus</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Task__c/Task__c.object-meta.xml
<CustomObject>
    <description>Task that is part of Project (Project can have up to 20 tasks)</description>
    <label>Task</label>
    <nameField>
        <label>Task Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Tasks</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Task__c/fields/Person__c.field-meta.xml
<CustomField>
    <fullName>Person__c</fullName>
    <description>Person responsible for Task</description>
    <label>Person</label>
    <referenceTo>Person__c</referenceTo>
    <relationshipLabel>Tasks</relationshipLabel>
    <relationshipName>Tasks</relationshipName>
    <relationshipOrder>1</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/classes/PersonBonusBatch.cls
public class PersonBonusBatch implements Database.Batchable<sObject>,  Schedulable{

    public void execute(SchedulableContext ctx) {
        PersonBonusBatch MonthlyPersonBonusBatch = new PersonBonusBatch();
        Id batchId = Database.executeBatch(MonthlyPersonBonusBatch);
   }
   
   

    public Database.QueryLocator start(Database.BatchableContext bc) {
        return Database.getQueryLocator(
        [SELECT Id, Bonus__c FROM Person__c]
        );
    }

    public void execute(Database.BatchableContext bc, List<Person__c> people) {
        Set <Id> peopleSet = new Set<Id>();
        for (Person__c person : people){
            peopleSet.add(person.Id);
        }
        List <Task__c> tasks = 
            [SELECT Id, Person__c, End_Date__c 
            FROM Task__c 
            WHERE Status__c = : 'Completed' and Person__c IN :peopleSet];
        for (Person__c person : people){
            Integer countTasks = 0;
            for (Task__c task : tasks){
                Date todayDate = Date.today();
                Integer monthsBetween = task.End_Date__c.monthsBetween(todayDate);
                if (person.Id == task.Person__c&&monthsBetween==1){
                    countTasks++;
                }
            }
        person.Bonus__c=25*countTasks;
        }    
        update people;
             
     }

    public void finish(Database.BatchableContext bc) {
        
    }


}