force-app/main/default/objects/Person__c/fields/Full_Name__c.field-meta.xml
<CustomField>
    <fullName>Full_Name__c</fullName>
    <formula>First_Name__c &amp; &apos; &apos; &amp; Last_Name__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Full Name</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Person__c/fields/Total_Amount_of_Tasks__c.field-meta.xml
<CustomField>
    <fullName>Total_Amount_of_Tasks__c</fullName>
    <description>Total Amount of Tasks</description>
    <label>Total Amount of Tasks</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/classes/SyncOutPerson.cls
public class SyncOutPerson {
    @AuraEnabled(cacheable=false)
    public static String pesSyncOut(Id personId){
        HttpRequest req = new HttpRequest();

        req.setMethod('POST');

        req.setHeader('recordId','application/json');
        req.setEndpoint('https://avenga-school.herokuapp.com/push-data');
        
        Person__c person = [SELECT Id,	Is_Synced__c,Full_name__c,Total_Amount_of_Projects__c,Total_Amount_of_Tasks__c
                            FROM Person__c 
                            WHERE Id = : personId];

        String serializedPerson = JSON.serialize(person);
        req.setBody(serializedPerson);
        
        Http http = new Http();

        HTTPResponse res = http.send(req);
        if(res.getStatusCode()==200){
            person.Is_Synced__c = true;
            update person;
            return ('Person Sync is configured');
          }  
        return ('Person Sync is not yet configured');

    }

}