force-app/main/default/objects/Person__c/fields/Full_Name__c.field-meta.xml
<CustomField>
    <fullName>Full_Name__c</fullName>
    <formula>First_Name__c &amp; &apos; &apos; &amp; Last_Name__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Full Name</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Person__c/fields/Total_Amount_of_Tasks__c.field-meta.xml
<CustomField>
    <fullName>Total_Amount_of_Tasks__c</fullName>
    <description>Total Amount of Tasks</description>
    <label>Total Amount of Tasks</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/classes/TopPeopleController.cls
public with sharing class TopPeopleController {
    @AuraEnabled
    
    public static List <Person__c> getTopPeople (Integer limitNumber){
        List <Person__c> retunResult = 
               [SELECT Name, Full_Name__c,Total_Amount_of_Projects__c,Total_Amount_of_Tasks__c
               FROM Person__c
               WHERE Total_Amount_of_Projects__c!=null ORDER BY Total_Amount_of_Projects__c desc LIMIT:limitNumber];
        return retunResult;
    }
}